### ISSUE TITLE
Skoða hring

### ISSUE THREAD

**Issue by ofurtumi** [ofurtumi/hugbo-1#4]
Eftir að leikmaður spilar hring þá getur hann opnað hringinn og séð skor sitt á hringnum.

**Comment by ofurtumi** [comment]
Er þetta komið? hvað finnst ykkur @Gunnarbjo @hakoningir @SvanaBirgis

**Comment by Gunnarbjo** [comment]
Já, lookar vel og virkar allt

**Comment by ofurtumi** [comment]
Erum samt í augnablikinu ekki með leið til að fá meiri upplýsingar um hringi, spurning hvort við þurfum það fyrir forgjöf og par og ehv
